"""What a defense lane may not build, train or research, so nothing reaches past the walls.

Raiders, traders and siege are confined by terrain and walls, so nothing may carry them across
(transport ships), outrange the walls (ranged castle units, warships, trebuchets, castle
arrows), take units from others (monks) or add units outside the purchase caps (production
buildings and their units). Towers, houses, economy buildings, traders and villagers stay.

The tables were read from DE's data (empires2_x2_p1.dat, 63 civilizations, October 2026): what
villagers build (through builder unit 118) apart from houses, economy buildings, towers,
walls, gates and the market, university and blacksmith; everything docks train but the trade
cog; and everything monasteries, castles, Kreposts and Donjons train. Many of these become
available only when a lane reaches an age, through technologies the game researches for free,
so those technologies are disabled too; and reaching an age upgrades some buildings into new
forms, which the lane disables again once it has that age.
"""

from AoE2ScenarioParser.datasets.buildings import BuildingInfo
from AoE2ScenarioParser.datasets.techs import TechInfo
from AoE2ScenarioParser.datasets.trigger_lists.comparison import Comparison
from AoE2ScenarioParser.datasets.trigger_lists.object_attribute import ObjectAttribute
from AoE2ScenarioParser.datasets.trigger_lists.technology_state import TechnologyState
from AoE2ScenarioParser.datasets.units import UnitInfo

from ancienttdde.game.triggers import Game
from ancienttdde.scenario.triggers import TriggerHandle, condition, effect

# Conversions of monks and buildings, and a longer conversion range.
CONVERSIONS = ("ATONEMENT", "REDEMPTION", "BLOCK_PRINTING")
# Range that would carry castle arrows and fire ships past the walls.
WALL_RANGE = ("CRENELLATIONS", "GREEK_FIRE")
# Two more tiles of tower range. With Fletching, Bodkin Arrow and Bracer, towers reach 11
# tiles, and the nearest tiles of the next lane are 12 away.
TOWER_RANGE = ("EUPSEONG", "ARTILLERY")


def disable_objects(trigger: TriggerHandle, player: int, objects: tuple[int, ...]) -> None:
    for unit in objects:
        effect(
            trigger,
            "enable_disable_object",
            source_player=player,
            object_list_unit_id=unit,
            enabled=0,
        )


def restrict(game: Game, trigger: TriggerHandle, player: int) -> None:
    """Disable the restricted objects and what would make them available again."""
    disable_objects(trigger, player, tuple(OBJECTS))
    technologies = [*TECHNOLOGIES, *(TechInfo[name].ID for name in CONVERSIONS + WALL_RANGE)]
    for technology in technologies:
        effect(
            trigger,
            "enable_disable_technology",
            source_player=player,
            technology=technology,
            enabled=0,
        )
    silence(game, trigger, player)
    # Siege power-up trebuchets stay on their islets, packed or not.
    for unit in ("TREBUCHET", "TREBUCHET_PACKED"):
        game.set_attribute(trigger, player, UnitInfo[unit].ID, ObjectAttribute.MOVEMENT_SPEED, 0)


def silence(game: Game, trigger: TriggerHandle, player: int) -> None:
    """A bought castle keeps its population and research but fires no arrows, and monks only
    carry relics."""
    castle = BuildingInfo["CASTLE"].ID
    for attribute in (
        ObjectAttribute.MAXIMUM_RANGE,
        ObjectAttribute.TOTAL_MISSILES,
        ObjectAttribute.MAXIMUM_TOTAL_MISSILES,
    ):
        game.set_attribute(trigger, player, castle, attribute, 0)
    game.set_attribute(trigger, player, UnitInfo["MONK"].ID, ObjectAttribute.MAXIMUM_RANGE, 0)


def restrict_reach(game: Game, player: int) -> None:
    """Blacksmith and unique technologies add castle and monk range back; every second, the
    lane's castle and monks lose it again."""
    trigger = game.trigger(f"lane.p{player}.restrict.reach", looping=True)
    condition(trigger, "timer", timer=1)
    game.value(trigger, f"lane.p{player}.active", 1)
    silence(game, trigger, player)


def restrict_competitive(game: Game) -> None:
    """With rivals beside every lane, no tower may reach the next lane."""
    trigger = game.trigger("game.restrict.competitive", looping=False)
    game.value(trigger, "game.participants", 2, Comparison.LARGER_OR_EQUAL)
    for player in range(1, 8):
        for name in TOWER_RANGE:
            effect(
                trigger,
                "enable_disable_technology",
                source_player=player,
                technology=TechInfo[name].ID,
                enabled=0,
            )


def restrict_ages(game: Game, player: int) -> None:
    """Once a lane reaches an age, disable the building forms that age upgraded into."""
    prefix = f"lane.p{player}"
    for age, objects in AGE_UPGRADES.items():
        trigger = game.trigger(f"{prefix}.restrict.{age.lower()}", looping=False)
        game.value(trigger, f"{prefix}.active", 1)
        condition(
            trigger,
            "technology_state",
            source_player=player,
            technology=TechInfo[age].ID,
            quantity=TechnologyState.DONE,
        )
        disable_objects(trigger, player, objects)


# Object IDs and internal names, every age variant included.
OBJECTS: dict[int, str] = {
    8: "LNGBW",
    10: "ARRG3",
    11: "MOSUN",
    12: "Barracks Age1",
    13: "FSHSP",
    14: "ARRG4",
    20: "Barracks Age4",
    21: "GALLY",
    25: "TKNIT",
    30: "CRCH2",
    31: "CRCH3",
    32: "CRCH4",
    40: "CATAP",
    41: "GBRSK",
    42: "TREBU",
    45: "DOCK",
    46: "JANNI",
    47: "DOCK3",
    49: "SIWS",
    51: "DOCK4",
    73: "CHUKN",
    82: "CSTL",
    86: "STBL3",
    87: "ARRG",
    93: "PKEMN",
    101: "STBL",
    104: "CRCH",
    106: "HLEIF",
    125: "MONKX",
    132: "Barracks Age3",
    133: "DOCK2",
    150: "SIWS4",
    153: "STBL4",
    203: "HVASCO",
    232: "WBRSK",
    239: "MPCAV",
    250: "LNGBT",
    275: "CENTU",
    276: "WNDR",
    281: "TAXEM",
    282: "DERVI",
    291: "SMURI",
    331: "PTREB",
    358: "ISPKM",
    359: "HLBDM",
    420: "CANGA",
    440: "PETARD",
    442: "WARGA",
    484: "RTWC3X",
    493: "AHXBW",
    498: "Barracks Age2",
    527: "RMSHP",
    528: "CRMSH",
    529: "FRGAL",
    530: "ULGBW",
    531: "UTAXE",
    532: "HFGAL",
    533: "ULNGB",
    534: "UWBRS",
    539: "SGALY",
    545: "XPORT",
    553: "UCATA",
    554: "UTKNI",
    555: "UGBRS",
    556: "UDERV",
    557: "UJANI",
    558: "UMPCAV",
    559: "UCHUK",
    560: "USMUR",
    561: "UMOSU",
    597: "RTWC4X",
    617: "RTWC2X",
    621: "RTWC1X",
    691: "CNGAU",
    692: "VBRSK",
    694: "UVBRK",
    725: "JAGUAR",
    726: "JAGUARX",
    755: "TARKAN",
    757: "UTARK",
    759: "BHUSK",
    761: "BHUSKX",
    763: "PLUME",
    765: "UPLUM",
    771: "CONQI",
    773: "UCONQ",
    775: "MONKY",
    827: "WAGON",
    829: "UWAGO",
    831: "TURTL",
    832: "UTURT",
    844: "HYI",
    866: "GENOE",
    868: "GENOE_E",
    869: "UMAGYX",
    871: "UMAGYX",
    876: "BOYAR",
    878: "EBOYA",
    879: "KAMAY",
    881: "EKAMA",
    886: "TARKAN",
    887: "UTARK",
    1001: "ORGAN",
    1003: "EORGAN",
    1004: "CARAV",
    1006: "ECARAV",
    1007: "CAMAR",
    1009: "ECAMAR",
    1013: "GBETO",
    1015: "EGBETO",
    1016: "SHOTEL",
    1018: "ESHOTEL",
    1021: "FEITO",
    1022: "MONKBT",
    1038: "HTRISTAN",
    1103: "SFRGAL",
    1104: "SDGAL",
    1106: "HDAGNA",
    1120: "ELEBALI",
    1122: "EELEBALI",
    1123: "KARAM",
    1125: "EKARAM",
    1126: "ARAMBAI",
    1128: "EARAMBAI",
    1129: "RATAN",
    1131: "ERATAN",
    1145: "NINJA",
    1160: "HSUNDA",
    1164: "HJAYA",
    1166: "UELEA",
    1189: "HARBOR",
    1225: "KONNIK",
    1227: "EKONNIK",
    1228: "KESHIK",
    1230: "EKESHIK",
    1231: "KIPCHAK",
    1233: "EKIPCHAK",
    1234: "LEITIS",
    1236: "ELEITIS",
    1251: "KREPOST",
    1254: "KONNIK",
    1255: "EKONNIK",
    1260: "MKIPCHAK",
    1275: "HKHAN",
    1302: "DRAGS",
    1368: "WNDR",
    1369: "WNDR",
    1374: "IRWAR",
    1631: "HMBRK",
    1655: "COUSTILLIER",
    1657: "ECOUSTILLIER",
    1658: "SERJEANT",
    1659: "ESERJEANT",
    1660: "DSERJEANT",
    1661: "EDSERJEANT",
    1665: "DONJON",
    1701: "OBUCH",
    1703: "EOBUCH",
    1704: "HUSSITEWAGON",
    1706: "EHUSSITEWAGON",
    1723: "CRUSADERKNIGHT",
    1735: "URUMI",
    1737: "EURUMI",
    1738: "RATHA",
    1740: "ERATHA",
    1741: "CHAKRAM",
    1743: "ECHAKRAM",
    1747: "GHULAM",
    1749: "EGHULAM",
    1750: "THIRISADAI",
    1754: "CARAVANSERAI",
    1759: "RATHA2",
    1761: "ERATHA2",
    1771: "HKHAN",
    1786: "DPKEMN",
    1787: "DISPKM",
    1788: "DHLBDM",
    1790: "CENTURION",
    1792: "ECENTURION",
    1795: "DROMON",
    1800: "COMPBOW",
    1802: "ECOMPBOW",
    1803: "MONASPA",
    1805: "EMONASPA",
    1806: "FORTCRCH",
    1810: "SVMBAS",
    1811: "WARRIORPRIEST",
    1817: "QIZILBASH",
    1829: "EQIZILBASH",
    1908: "IRONPAG",
    1910: "EIRONPAG",
    1920: "LIAODAO",
    1922: "ELIAODAO",
    1948: "LOUCHUAN",
    1949: "TIGERCAV",
    1951: "ETIGERCAV",
    1954: "CAOCAO",
    1959: "WHTFTHRG",
    1961: "EWHTFTHRG",
    1966: "LIUBEI",
    1968: "FIREARCHER",
    1970: "EFIREARCHER",
    1978: "SUNJIAN",
    2060: "HALLOFHEROES",
    2101: "Immortal",
    2102: "Elite Immortal",
    2104: "Strategos",
    2105: "Elite Strategos",
    2107: "Hippeus",
    2108: "Elite Hippeus",
    2117: "Shipyard3",
    2118: "Shipyard4",
    2119: "Shipyard2",
    2141: "Port 4",
    2142: "Port 3",
    2143: "Port 2",
    2168: "Hippeus",
    2169: "Elite Hippeus",
    2172: "Port 1",
    2174: "Immortal Ranged",
    2175: "Elite Immortal Ranged",
    2227: "Strategos with Taxiarchs",
    2228: "Elite Strategos with Taxiarchs",
    2315: "Themistocles",
    2316: "Leonidas",
    2318: "Lysander",
    2326: "Cretan Archer",
    2329: "Sparabara",
    2331: "Sickle Warrior",
    2346: "Cleon",
    2348: "Oracle Temple",
    2356: "Antiquity Mode Fishing Ship",
    2382: "Companion Cavalry",
    2383: "Elite Companion Cavalry",
    2386: "Rhomphaia Warrior",
    2387: "Elite Rhomphaia Warrior",
    2388: "Pattiyodha Longbowman",
    2389: "Elite Pattiyodha Longbowman",
    2397: "Alexander Dismounted",
    2400: "Parmenion",
    2402: "Hephaistion",
    2414: "Macedonian Command Post",
    2415: "Fortified Outpost",
    2417: "Fortified Outpost",
    2418: "CSTL",
    2419: "Pattiyodha Longbowman",
    2420: "Elite Pattiyodha Longbowman",
    2436: "Porus",
    2437: "Camp Barracks",
    2438: "Camp Archery Range",
    2439: "Camp Stable",
    2440: "Camp Siege Workshop",
    2441: "Camp Blacksmith",
    2556: "SETTL1",
    2558: "SETTL2",
    2560: "SETTL3",
    2562: "GUECHA",
    2564: "EGUECHA",
    2565: "GUECHA_D0",
    2566: "KONA",
    2568: "EKONA",
    2579: "BLCKWOOD",
    2581: "EBLCKWOOD",
    2586: "Temple Guard",
    2587: "Elite Temple Guard",
    2626: "Hulk",
    2627: "War hulk",
    2628: "Carrack",
    2630: "WHALING_SHIP",
    2633: "CATAGA",
    2638: "HGALVARINO",
    2705: "Hearth Troop",
    2706: "Elite Hearth Troop",
    2708: "Jarl",
    2709: "Elite Jarl",
    2711: "Jomsviking",
    2712: "Elite Jomsviking",
    2728: "HLNGS",
}

# Technologies that make a restricted object available or upgrade into one.
TECHNOLOGIES: dict[int, str] = {
    1: "Tarkan (make avail)",
    2: "Elite Tarkan",
    16: "Gothic Anarchy",
    25: "STBL (make avail)",
    26: "Plumed Archer (make avail)",
    27: "Elite Plumed Archer",
    34: "War Galley",
    37: "Cannon Galleon",
    58: "Conquistador (make avail)",
    60: "Elite Conquistador",
    84: "Missionary (avail)",
    87: "Spearman (make avail)",
    137: "Castle -- Age Three",
    144: "Wonder Plans",
    147: "ARRG (make avail)",
    149: "Siege Wksp (make avail)",
    157: "Monk (make avail)",
    187: "R TC (make avail)",
    197: "Pikeman",
    210: "Church (make avail)",
    220: "Barracks (make avail)",
    240: "Make Scout Ship Avail",
    243: "Make Fire Galley Avail",
    244: "Heavy Demolition",
    246: "Fast Fire Ship",
    256: "Trebuchet",
    262: "Samurai (make avail)",
    263: "Longbow (make avail)",
    267: "Cataphract (make avail)",
    268: "Chu-Ko-Nu (make avail)",
    269: "Mameluke (make avail)",
    271: "Jannisary (make avail)",
    272: "Longship (make avail)",
    273: "Mobile Siege Unit (make avail)",
    274: "War Elephant (make avail)",
    275: "Throwing Axemen (make avail)",
    276: "Teutonic Knight (make avail)",
    277: "Woad Berserker (make avail)",
    354: "Turk Castle",
    360: "Elite Longbow",
    361: "Elite Cataphract",
    362: "Elite Chu Ko Nu",
    363: "Elite Throwing Axemen",
    364: "Elite Teutonic Knight",
    365: "Elite Huskarl",
    366: "Elite Samurai",
    367: "Elite War Elephant",
    368: "Elite Mameluke",
    369: "Elite Jannisary",
    370: "Elite Woad Raider",
    371: "Elite Mangudai",
    372: "Unique Heroic Viking LBT",
    376: "Elite Cannon Galley",
    398: "Elite Berserk",
    399: "Berserk",
    426: "Petard (make avail)",
    429: "Halberdier",
    431: "Jaguar Man",
    432: "Elite Jaguar Man",
    446: "Huskarl (make avail)",
    447: "Turtle Ship (make avail)",
    448: "Elite Turtle Ship",
    449: "War Wagon",
    450: "Elite War Wagon",
    467: "Genoese Bow (make avail)",
    468: "Elite Genoese Bow",
    471: "Magyar Huszar (make avail)",
    472: "Elite Magyar Huszar",
    483: "Huns UT",
    503: "Boyar (make avail)",
    504: "Elite Siege Tower",
    508: "Kamayuk (make avail)",
    509: "Elite Kamayuk",
    518: "Caravanserai (make avail)",
    552: "Caravanserai (make avail)",
    562: "Organ Gun (make avail)",
    563: "Elite Organ Gun",
    564: "Camel Archer (make avail)",
    565: "Elite Camel Archer",
    566: "Gbeto (make avail)",
    567: "Elite Mali Unit",
    568: "Shotel Warrior (make avail)",
    569: "Elite Ethiopia Unit",
    570: "Feitoria (make avail)",
    596: "Caravel (make avail)",
    597: "Elite Caravel",
    604: "Fire Galley (make avail)",
    605: "Demo Galley (make avail)",
    614: "Ballista Elephant (make avail)",
    615: "Elite Ballista Elephant",
    616: "Karambit Warrior (make avail)",
    617: "Elite Karambit Warrior",
    618: "Arambai (make avail)",
    619: "Elite Arambai",
    620: "Rattan Archer (make avail)",
    621: "Elite Rattan Archer",
    624: "Malay UT",
    677: "Konnik (make avail)",
    678: "Elite Konnik",
    679: "Keshik (make avail)",
    680: "Elite Keshik",
    681: "Kipchak (make avail)",
    682: "Elite Kipchak",
    683: "Leitis (make avail)",
    684: "Elite Leitis",
    695: "C-Bonus, Enable Krepost",
    706: "Upgrade Rams in Castle",
    712: "Upgrade Rams",
    750: "Coustillier (make avail)",
    751: "Elite Coustillier",
    752: "Serjeant (make avail)",
    753: "Elite Serjeant",
    775: "C-Bonus, Enable Donjon",
    778: "Obuch (make avail)",
    779: "Elite Obuch",
    780: "Hussite Wagon (make avail)",
    781: "Elite Hussite Wagon",
    825: "Urumi Swordsman (make avail)",
    826: "Elite Urumi Swordsman",
    827: "Ratha (make avail)",
    828: "Elite Ratha",
    829: "Chakram Thrower (make avail)",
    830: "Elite Chakram Thrower",
    839: "Ghulam (make avail)",
    840: "Elite Ghulam",
    841: "Thirisadai (make avail)",
    881: "Centurion (make avail)",
    882: "Elite Centurion",
    886: "Dromon (make avail)",
    903: "Hulk (make avail)",
    904: "Carrack",
    905: "Demolition Ship",
    911: "Galleon",
    913: "Catapult Galleon (make avail)",
    917: "Composite Bowman (make avail)",
    918: "Elite Composite Bowman",
    919: "Monaspa (make avail)",
    920: "Elite Monaspa",
    930: "Fortified Church (Georgians)",
    941: "Fortified Church (Armenians)",
    948: "Warrior Priest (make avail)",
    967: "Elite Qizilbash Warrior",
    990: "Iron Pagoda (make avail)",
    991: "Elite Iron Pagoda",
    1001: "Liao Dao (make avail)",
    1002: "Elite Liao Dao",
    1010: "Dragon Ship",
    1034: "Lou Chuan (make avail)",
    1035: "Tiger Cavalry (make avail)",
    1036: "Elite Tiger Cavalry",
    1063: "White Feather Guard (make avail)",
    1064: "Elite White Feather Guard",
    1073: "Fire Archer (make avail)",
    1074: "Elite Fire Archer",
    1115: "Elite Immortal",
    1125: "Elite Strategos",
    1135: "Elite Hippeus",
    1270: "Fortified Outpost",
    1289: "Elite Companion",
    1301: "Elite Rhomphaia Warrior",
    1326: "Elite Pattiyodha Longbowman",
    1353: "Settlement (make avail)",
    1354: "Settlement Age2 upgrade",
    1355: "Settlement Age3 upgrade",
    1363: "Guecha Warrior (make avail)",
    1364: "Guecha Warrior Pagoda",
    1375: "Kona (make avail)",
    1376: "Elite Kona",
    1388: "Blackwood Archer (make avail)",
    1389: "Elite Blackwood Archer",
    1400: "Temple Guard (make avail)",
    1401: "Elite Temple Guard",
    1462: "Elite Hearth Troop",
    1471: "Jarl (make avail)",
    1472: "Elite Jarl",
    1481: "Jomsviking (make avail)",
    1482: "Elite Jomsviking",
}

AGE_UPGRADES: dict[str, tuple[int, ...]] = {
    "CASTLE_AGE": (
        10,
        31,
        47,
        86,
        132,
        484,
        2117,
        2142,
    ),
    "IMPERIAL_AGE": (
        14,
        20,
        32,
        51,
        153,
        597,
        2118,
        2141,
    ),
}
